packages:
  fin-analytics/internal/cache:
    interfaces:
      StatsCache:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"

  fin-analytics/internal/grpcclient:
    interfaces:
      TransactionClient:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"

  fin-analytics/internal/kafka:
    interfaces:
      EventPublisher:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"