packages:
  fin-track-app/internal/finanalytics/cache:
    interfaces:
      StatsCache:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"

  fin-track-app/internal/finanalytics/grpcclient:
    interfaces:
      TransactionClient:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"

  fin-track-app/internal/finapi/repository:
    interfaces:
      TransactionRepository:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"

  fin-track-app/internal/kafka:
    interfaces:
      EventPublisher:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mocks.go"
          pkgname: "mocks"
          structname: "{{.InterfaceName}}"