// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fin-analytics/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionClient creates a new instance of MockTransactionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionClient {
	mock := &MockTransactionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionClient is an autogenerated mock type for the TransactionClient type
type MockTransactionClient struct {
	mock.Mock
}

type MockTransactionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionClient) EXPECT() *MockTransactionClient_Expecter {
	return &MockTransactionClient_Expecter{mock: &_m.Mock}
}

// FetchTransactions provides a mock function for the type MockTransactionClient
func (_mock *MockTransactionClient) FetchTransactions(ctx context.Context, userID int) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactions")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []domain.Transaction); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionClient_FetchTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTransactions'
type MockTransactionClient_FetchTransactions_Call struct {
	*mock.Call
}

// FetchTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionClient_Expecter) FetchTransactions(ctx interface{}, userID interface{}) *MockTransactionClient_FetchTransactions_Call {
	return &MockTransactionClient_FetchTransactions_Call{Call: _e.mock.On("FetchTransactions", ctx, userID)}
}

func (_c *MockTransactionClient_FetchTransactions_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionClient_FetchTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionClient_FetchTransactions_Call) Return(transactions []domain.Transaction, err error) *MockTransactionClient_FetchTransactions_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionClient_FetchTransactions_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]domain.Transaction, error)) *MockTransactionClient_FetchTransactions_Call {
	_c.Call.Return(run)
	return _c
}
