// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fin-analytics/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewStatsCache creates a new instance of StatsCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsCache {
	mock := &StatsCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatsCache is an autogenerated mock type for the StatsCache type
type StatsCache struct {
	mock.Mock
}

type StatsCache_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsCache) EXPECT() *StatsCache_Expecter {
	return &StatsCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type StatsCache
func (_mock *StatsCache) Get(ctx context.Context, userID int) (*domain.FinanceStats, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.FinanceStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.FinanceStats, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.FinanceStats); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FinanceStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatsCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StatsCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *StatsCache_Expecter) Get(ctx interface{}, userID interface{}) *StatsCache_Get_Call {
	return &StatsCache_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *StatsCache_Get_Call) Run(run func(ctx context.Context, userID int)) *StatsCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StatsCache_Get_Call) Return(financeStats *domain.FinanceStats, err error) *StatsCache_Get_Call {
	_c.Call.Return(financeStats, err)
	return _c
}

func (_c *StatsCache_Get_Call) RunAndReturn(run func(ctx context.Context, userID int) (*domain.FinanceStats, error)) *StatsCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type StatsCache
func (_mock *StatsCache) Set(ctx context.Context, stats domain.FinanceStats) error {
	ret := _mock.Called(ctx, stats)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FinanceStats) error); ok {
		r0 = returnFunc(ctx, stats)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatsCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type StatsCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - stats domain.FinanceStats
func (_e *StatsCache_Expecter) Set(ctx interface{}, stats interface{}) *StatsCache_Set_Call {
	return &StatsCache_Set_Call{Call: _e.mock.On("Set", ctx, stats)}
}

func (_c *StatsCache_Set_Call) Run(run func(ctx context.Context, stats domain.FinanceStats)) *StatsCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FinanceStats
		if args[1] != nil {
			arg1 = args[1].(domain.FinanceStats)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StatsCache_Set_Call) Return(err error) *StatsCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatsCache_Set_Call) RunAndReturn(run func(ctx context.Context, stats domain.FinanceStats) error) *StatsCache_Set_Call {
	_c.Call.Return(run)
	return _c
}
