// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fin-track-app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) CreateTransaction(ctx context.Context, tx domain.Transaction) (domain.Transaction, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) (domain.Transaction, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) domain.Transaction); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockTransactionRepository_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx domain.Transaction
func (_e *MockTransactionRepository_Expecter) CreateTransaction(ctx interface{}, tx interface{}) *MockTransactionRepository_CreateTransaction_Call {
	return &MockTransactionRepository_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, tx)}
}

func (_c *MockTransactionRepository_CreateTransaction_Call) Run(run func(ctx context.Context, tx domain.Transaction)) *MockTransactionRepository_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_CreateTransaction_Call) Return(transaction domain.Transaction, err error) *MockTransactionRepository_CreateTransaction_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_CreateTransaction_Call) RunAndReturn(run func(ctx context.Context, tx domain.Transaction) (domain.Transaction, error)) *MockTransactionRepository_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransaction provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) DeleteTransaction(ctx context.Context, userID int, transactionID int64) error {
	ret := _mock.Called(ctx, userID, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) error); ok {
		r0 = returnFunc(ctx, userID, transactionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_DeleteTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransaction'
type MockTransactionRepository_DeleteTransaction_Call struct {
	*mock.Call
}

// DeleteTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - transactionID int64
func (_e *MockTransactionRepository_Expecter) DeleteTransaction(ctx interface{}, userID interface{}, transactionID interface{}) *MockTransactionRepository_DeleteTransaction_Call {
	return &MockTransactionRepository_DeleteTransaction_Call{Call: _e.mock.On("DeleteTransaction", ctx, userID, transactionID)}
}

func (_c *MockTransactionRepository_DeleteTransaction_Call) Run(run func(ctx context.Context, userID int, transactionID int64)) *MockTransactionRepository_DeleteTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_DeleteTransaction_Call) Return(err error) *MockTransactionRepository_DeleteTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_DeleteTransaction_Call) RunAndReturn(run func(ctx context.Context, userID int, transactionID int64) error) *MockTransactionRepository_DeleteTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserTransactions provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) ListUserTransactions(ctx context.Context, userID int) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserTransactions")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []domain.Transaction); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_ListUserTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserTransactions'
type MockTransactionRepository_ListUserTransactions_Call struct {
	*mock.Call
}

// ListUserTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionRepository_Expecter) ListUserTransactions(ctx interface{}, userID interface{}) *MockTransactionRepository_ListUserTransactions_Call {
	return &MockTransactionRepository_ListUserTransactions_Call{Call: _e.mock.On("ListUserTransactions", ctx, userID)}
}

func (_c *MockTransactionRepository_ListUserTransactions_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionRepository_ListUserTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_ListUserTransactions_Call) Return(transactions []domain.Transaction, err error) *MockTransactionRepository_ListUserTransactions_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_ListUserTransactions_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]domain.Transaction, error)) *MockTransactionRepository_ListUserTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransaction provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) UpdateTransaction(ctx context.Context, tx domain.Transaction) (domain.Transaction, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) (domain.Transaction, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) domain.Transaction); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_UpdateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransaction'
type MockTransactionRepository_UpdateTransaction_Call struct {
	*mock.Call
}

// UpdateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx domain.Transaction
func (_e *MockTransactionRepository_Expecter) UpdateTransaction(ctx interface{}, tx interface{}) *MockTransactionRepository_UpdateTransaction_Call {
	return &MockTransactionRepository_UpdateTransaction_Call{Call: _e.mock.On("UpdateTransaction", ctx, tx)}
}

func (_c *MockTransactionRepository_UpdateTransaction_Call) Run(run func(ctx context.Context, tx domain.Transaction)) *MockTransactionRepository_UpdateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateTransaction_Call) Return(transaction domain.Transaction, err error) *MockTransactionRepository_UpdateTransaction_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_UpdateTransaction_Call) RunAndReturn(run func(ctx context.Context, tx domain.Transaction) (domain.Transaction, error)) *MockTransactionRepository_UpdateTransaction_Call {
	_c.Call.Return(run)
	return _c
}
