// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fin-track-app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher {
	mock := &EventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher struct {
	mock.Mock
}

type EventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisher) EXPECT() *EventPublisher_Expecter {
	return &EventPublisher_Expecter{mock: &_m.Mock}
}

// PublishTransactions provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishTransactions(ctx context.Context, msg domain.TransactionMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TransactionMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTransactions'
type EventPublisher_PublishTransactions_Call struct {
	*mock.Call
}

// PublishTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - msg domain.TransactionMessage
func (_e *EventPublisher_Expecter) PublishTransactions(ctx interface{}, msg interface{}) *EventPublisher_PublishTransactions_Call {
	return &EventPublisher_PublishTransactions_Call{Call: _e.mock.On("PublishTransactions", ctx, msg)}
}

func (_c *EventPublisher_PublishTransactions_Call) Run(run func(ctx context.Context, msg domain.TransactionMessage)) *EventPublisher_PublishTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TransactionMessage
		if args[1] != nil {
			arg1 = args[1].(domain.TransactionMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishTransactions_Call) Return(err error) *EventPublisher_PublishTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishTransactions_Call) RunAndReturn(run func(ctx context.Context, msg domain.TransactionMessage) error) *EventPublisher_PublishTransactions_Call {
	_c.Call.Return(run)
	return _c
}
